add scripts

diff --git a/instruqt-tracks/prosimo-lab-observe-and-troubleshoot/03-build-multi-cloud-transit/check-shell b/instruqt-tracks/prosimo-lab-observe-and-troubleshoot/03-build-multi-cloud-transit/check-shell
--- a/instruqt-tracks/prosimo-lab-observe-and-troubleshoot/03-build-multi-cloud-transit/check-shell
+++ b/instruqt-tracks/prosimo-lab-observe-and-troubleshoot/03-build-multi-cloud-transit/check-shell
@@ -1,11 +1,69 @@
-#!/bin/sh
-#
-# This script runs when the platform check the challenge.
-#
-# The platform determines if the script was successful using the exit code of this
-# script. If the exit code is not 0, the script fails. 
-#
+#!/bin/bash
 
-echo "This is the check script"
+# Enable strict mode for script execution
+set -euo pipefail
 
-exit 0
+cd /root/prosimo-lab/assets/terraform/
+
+# Run terraform output command and store the output in a variable
+output=$(terraform output -json)
+
+# Initialize the fail_message variable as an empty string
+fail_message=""
+
+# Function to extract the first SSH command from the first region
+get_first_ssh_command() {
+    echo "$output" | jq -r '.ssh_access_aws_eu.value[0]' | grep "ssh -i"
+}
+
+# Define a list of IP addresses to test
+ips=("10.0.0.100" "10.1.0.100" "10.2.0.100" "10.3.0.100" "10.5.0.100")
+#ips=("10.4.0.100")
+
+# Generate a remote command to run ping tests
+generate_ping_test_command() {
+    local remote_commands=("connectivity_check=0;")
+    for ip in "${ips[@]}"; do
+        # Adding a ping command for each IP
+        remote_commands+=("ping -c 1 $ip &> /dev/null || connectivity_check=1;")
+    done
+    # Adding the final check and fail message
+    remote_commands+=("if [ \$connectivity_check -eq 0 ]; then echo 'SUCCESS: Connectivity OK'; else echo 'FAIL: Connectivity has not been built correctly'; fi")
+    # Joining all commands to run sequentially
+    echo "${remote_commands[*]}"
+}
+
+# Main execution
+# Checking if jq is installed
+if ! command -v jq &> /dev/null; then
+    echo "jq is not installed. Please install jq to parse the JSON output."
+    exit 1
+fi
+
+# Extracting the first SSH command
+ssh_command=$(get_first_ssh_command)
+
+# Check if an SSH command was found
+if [ -z "$ssh_command" ]; then
+    fail_message="FAIL: Terraform deployment failed - not all resources have been deployed."
+fi
+
+# Modify the SSH command to automatically accept host key and run ping tests
+ping_test_command=$(generate_ping_test_command)
+ssh_command=$(echo $ssh_command | awk -F '=> ' '{print $2}' | sed "s/ssh /ssh -o StrictHostKeyChecking=no /")
+full_command="$ssh_command '$ping_test_command'"
+
+# Executing the SSH command with ping tests
+echo "Executing SSH and running ping tests..."
+eval "$full_command"
+result=$?
+
+# Check the result of the SSH command
+if [ $result -eq 0 ]; then
+    echo "SSH and ping test executed successfully."
+    exit 0
+else
+    fail_message="FAIL: Connectivity test failed."
+    echo "$fail_message"
+    exit $result
+fi
diff --git a/instruqt-tracks/prosimo-lab-observe-and-troubleshoot/05-troubleshoot-multi-cloud-networking/check-shell b/instruqt-tracks/prosimo-lab-observe-and-troubleshoot/05-troubleshoot-multi-cloud-networking/check-shell
--- a/instruqt-tracks/prosimo-lab-observe-and-troubleshoot/05-troubleshoot-multi-cloud-networking/check-shell
+++ b/instruqt-tracks/prosimo-lab-observe-and-troubleshoot/05-troubleshoot-multi-cloud-networking/check-shell
@@ -1,11 +1,61 @@
-#!/bin/sh
-#
-# This script runs when the platform check the challenge.
-#
-# The platform determines if the script was successful using the exit code of this
-# script. If the exit code is not 0, the script fails. 
-#
+#!/bin/bash
 
-echo "This is the check script"
+# Enable strict mode for script execution
+set -euo pipefail
 
-exit 0
+# Define constants
+REGION="us-east-1"
+SG_NAME="sc_allow_ssh"
+INSTANCE_NAME="WebServerProdUs1"
+
+# Fetch the Instance IDs for instances with name WebSvcsProdUs
+INSTANCE_IDS=$(aws ec2 describe-instances --region $REGION --filters "Name=tag:Name,Values=$INSTANCE_NAME" --query "Reservations[*].Instances[*].InstanceId" --output text)
+
+# Check if INSTANCE_IDS is empty
+if [ -z "$INSTANCE_IDS" ]; then
+    echo "No EC2 instance with name '$INSTANCE_NAME' found in region $REGION."
+    exit 1
+fi
+
+# Function to check outbound rules
+check_outbound_rules() {
+    local sg_id=$1
+    local outbound_rules=$(aws ec2 describe-security-groups --region $REGION --group-ids $sg_id --query "SecurityGroups[*].IpPermissionsEgress")
+
+    if echo $outbound_rules | grep -q '"IpProtocol": "-1"'; then
+        echo "Security Group with ID $sg_id allows all outbound traffic."
+        return 0
+    else
+        echo "Security Group with ID $sg_id does not allow all outbound traffic."
+        return 1
+    fi
+}
+
+# Main logic
+all_allow_outbound=true
+for instance_id in $INSTANCE_IDS; do
+    # Fetch associated SGs for each instance
+    SG_IDS=$(aws ec2 describe-instances --instance-ids $instance_id --region $REGION --query "Reservations[*].Instances[*].SecurityGroups[?GroupName=='$SG_NAME'].GroupId" --output text)
+
+    if [ -z "$SG_IDS" ]; then
+        echo "No Security Group with name '$SG_NAME' found for instance ID $instance_id."
+        all_allow_outbound=false
+        break # Break out of the loop
+    fi
+
+    for sg_id in $SG_IDS; do
+        if ! check_outbound_rules $sg_id; then
+            all_allow_outbound=false
+            break 2 # Break out of both loops
+        fi
+    done
+done
+
+if $all_allow_outbound; then
+    echo "Configuration is correct"
+    exit 0
+else
+    fail_message="FAIL: Connectivity test failed."
+    echo "$fail_message"
+
+fi
